name: Android CI (Cloud Build)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Ye naya step GitHub server me Gradle software install karega
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.0' 

    # Ab ye command 100% chalegi bina kisi error ke
    - name: Build APK
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: SecureDating-App
        path: app/build/outputs/apk/debug/app-debug.apk
